Feature/zip code voting
Pipeline-to-Power/decidim-module-ptp pull request #7
Opened 2023-05-04 11:23 UTC by sinaeftekhar

This pull request enables zip code voting, while maintaining the the main functionality of the module. 
After installing, admins would be able to enable "zip code" workflow, and users will be able to vote in accordance to their zip codes.
Complete description of this pull request can be found [here](https://github.com/Pipeline-to-Power/decidim-module-ptp/tree/feature/zip-code-voting/decidim-budgets_booth)

2023-06-05 13:55 UTC, ahukkanen requested changes
Great work!

I have added some general cleanup notes and I've also found out one bug when testing this out (missing voting terms when ZIP code voting is not enabled).

Could you please have a look and then we can finally merge this back to the main branch: :tada:

2023-06-05 13:55 UTC, ahukkanen commented on decidim-budgets_booth/spec/shared/cancel_voting.rb
>  # frozen_string_literal: true
Please name this shared spec correctly. A shared spec containing examples should have `_examples.rb` suffix.

2023-06-05 13:55 UTC, ahukkanen commented on decidim-budgets_booth/spec/shared/ensure_user_data.rb
> +# frozen_string_literal: true
Please name this shared spec correctly. A shared spec containing examples should have `_examples.rb` suffix.

2023-06-05 13:55 UTC, ahukkanen commented on decidim-budgets_booth/spec/shared/ensure_user_sign_in.rb
> +# frozen_string_literal: true
Please name this shared spec correctly. A shared spec containing examples should have `_examples.rb` suffix.

2023-06-05 13:55 UTC, ahukkanen commented on decidim-budgets_booth/spec/shared/ensure_zip_code_workflow.rb
> +# frozen_string_literal: true
Please name this shared spec correctly. A shared spec containing examples should have `_examples.rb` suffix.

2023-06-05 13:55 UTC, ahukkanen commented on decidim-budgets_booth/spec/shared/filtering_projects.rb
>  # frozen_string_literal: true
Please name this shared spec correctly. A shared spec containing examples should have `_examples.rb` suffix.

2023-06-05 13:55 UTC, ahukkanen commented on decidim-budgets_booth/spec/shared/non_voting_views.rb
>  # frozen_string_literal: true
Please name this shared spec correctly. A shared spec containing examples should have `_examples.rb` suffix.

2023-06-05 13:55 UTC, ahukkanen commented on decidim-budgets_booth/spec/shared/not_allowable_voting.rb
> +# frozen_string_literal: true
Please name this shared spec correctly. A shared spec containing examples should have `_examples.rb` suffix.

2023-06-05 13:55 UTC, ahukkanen commented on decidim-budgets_booth/spec/shared/render_new_zip_code_page.rb
> +# frozen_string_literal: true
Please name this shared spec correctly. A shared spec containing examples should have `_examples.rb` suffix.

Also, be consistent when calling `RSpec.shared_examples` vs just `shared_examples` in some shared specs. Pick one convention and stick with that one.

2023-06-05 13:55 UTC, ahukkanen commented on decidim-budgets_booth/spec/shared/shared_context.rb
> +RSpec.shared_context "with scopes" do
Be consistent when calling these methods through the `RSpec` class vs leaving it out. In some shared examples for example, you are calling directly the `shared_examples` method without the `RSpec.` prefix.

2023-06-05 13:55 UTC, ahukkanen commented on decidim-budgets_booth/spec/shared/sorting_projects.rb
Please name this shared spec correctly. A shared spec containing examples should have `_examples.rb` suffix.

2023-06-05 13:55 UTC, ahukkanen commented on decidim-budgets_booth/zip-code-workflow.png
Maybe this image should be under the `docs` folder?

2023-06-05 13:55 UTC, ahukkanen commented on decidim-budgets_booth/app/views/decidim/budgets/voting/_confirm_voting_modal.html.erb
>  <% if current_order.present? %>
When the ZIP code voting is not enabled, we should show the voting terms in the confirm modal like we used to do on the confirm page (this was a request from Francesco):
![Confirm vote modal](https://github.com/Pipeline-to-Power/decidim-module-ptp/assets/864340/72d1c9c1-feee-4791-b388-3ec3ad8c06e2)

In the previous version, we used to have this on the confirm vote page:
![Confirm page](https://github.com/Pipeline-to-Power/decidim-module-ptp/assets/864340/d80c1495-bd93-450d-a914-d9eb75878961)

Now we are not displaying this text anywhere when the ZIP code voting is not enabled.

We should add this text back to the confirm vote modal **but only if ZIP code voting is not enabled**. When ZIP code voting is enabled, we already show this message when entering the voting booth, so the user has already confirmed it there.

2023-06-06 13:19 UTC, ahukkanen requested changes
Few more things noticed, we are really close merging this one!

2023-06-06 13:19 UTC, ahukkanen commented on decidim-budgets_booth/config/initializers/decidim_budgets_workflow.rb
> +Decidim::Budgets.workflows[:zip_code] = Decidim::BudgetsBooth::Workflows::ZipCode
You have properly moved this logic to the engine initializer but this file is still here, so we should remove it.

2023-06-06 13:19 UTC, ahukkanen commented on decidim-budgets_booth/README.md
>  ## Usage
Make the file more readable by adding proper spacing.
```suggestion

## Usage
```

2023-06-06 13:19 UTC, ahukkanen commented on decidim-budgets_booth/README.md
> +For enabling the "ZIP code voting" feature, you have a new workflow available for the budgets component named "ZIP code" which shows up at the configuration page as follows:
Add a paragraph break.
```suggestion

For enabling the "ZIP code voting" feature, you have a new workflow available for the budgets component named "ZIP code" which shows up at the configuration page as follows:
```

2023-06-06 13:19 UTC, ahukkanen commented on decidim-budgets_booth/README.md
> +This workflow enables the following features to the budget voting experience:
Add a paragraph break.
```suggestion

This workflow enables the following features to the budget voting experience:
```

2023-06-06 13:19 UTC, ahukkanen commented on decidim-budgets_booth/README.md
> +```ruby
Make the file more readable by adding proper spacing.
```suggestion

```ruby
```

2023-06-06 13:19 UTC, ahukkanen commented on .rubocop_ruby.yml
> +    - "development_app/**/*"
This has not been change as suggested. This would not exclude a version specific development app now such as `development_app_026`.

Take a look a the core exclude rule carefully:

https://github.com/decidim/decidim/blob/6209f88f9910436943fd4d61e247d55d81cb8f7f/decidim-dev/config/rubocop/ruby.yml#L16

2023-06-06 13:19 UTC, ahukkanen commented on decidim-budgets_booth/spec/shared/shared_context.rb
> +RSpec.shared_context "with scopes" do
We are still using a mixed style regarding calling these methods through the `RSpec` class comparing to the shared examples (please review all these cases and stick to one convention).

2023-06-06 13:19 UTC, ahukkanen commented on decidim-budgets_booth/spec/shared/render_new_zip_code_page_examples.rb
> +RSpec.shared_examples "rendering new zip code page" do |zip_code_length|
Here we still have mixed styling regarding calling the `shared_examples` and `shared_context` methods.

2023-06-06 13:19 UTC, ahukkanen commented on decidim-budgets_booth/app/views/decidim/budgets/projects/_budget_confirm.html.erb
> +          <h3 class="text-center"><%= t(".is_this_correct") %></h3>
Great! But there is still a small problem regarding this, the heading levels are the same for the modal's main title and this title:
![Heading order](https://github.com/Pipeline-to-Power/decidim-module-ptp/assets/864340/0ab09c90-6f48-4d22-b041-c876cf136587)

The heading order needs to be hierarchical, i.e. the second title within the same context needs to be on 1 level lower than the modal's "main" title.

Also check the indentation in this file to make it more readable for others as well. There are some inconsistencies.

2023-06-07 07:11 UTC, sinaeftekhar commented on decidim-budgets_booth/lib/decidim/budgets_booth/voting_extensions.rb
> +    module VotingExtensions
What about VotingSupport, or VotingUtilities?

2023-06-07 13:05 UTC, ahukkanen approved these changes
:+1:

2023-06-07 13:05 UTC, merged